### ISSUE TITLE
netlify-cli@v2.42.0でデプロイがこける問題

### ISSUE THREAD

**Issue by youyo** [covid19-aomori/website#112]
```
npx netlify-cli deploy --dir=./dist --prod
TypeError: Cannot read property 'replace' of null
    at resolvePath (/home/circleci/.npm/_npx/497/lib/node_modules/netlify-cli/node_modules/@netlify/config/src/files.js:36:22)
    at searchBaseConfigFile (/home/circleci/.npm/_npx/497/lib/node_modules/netlify-cli/node_modules/@netlify/config/src/path.js:44:20)
    at getConfigPath (/home/circleci/.npm/_npx/497/lib/node_modules/netlify-cli/node_modules/@netlify/config/src/path.js:20:7)
    at getFullConfig (/home/circleci/.npm/_npx/497/lib/node_modules/netlify-cli/node_modules/@netlify/config/src/main.js:140:28)
    at loadConfig (/home/circleci/.npm/_npx/497/lib/node_modules/netlify-cli/node_modules/@netlify/config/src/main.js:112:13)
    at resolveConfig (/home/circleci/.npm/_npx/497/lib/node_modules/netlify-cli/node_modules/@netlify/config/src/main.js:59:40)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Exited with code exit status 1
```

https://github.com/netlify/cli/issues/809

**Comment by youyo** [comment]
v2.41.0 を使用するように変更
